### ISSUE TITLE
Error installing new package

### ISSUE THREAD

**Issue by pstvasko** [ofekb/n8n-nodes-telegram-client#1]
Hello. I'm getting errors when trying to install; I've tried different methods. n8n 1.66.0

Error installing new package
Error loading package "n8n-nodes-telegram-client" :The specified package could not be loaded

**Comment by kharlakov** [comment]
I'm having the exact same problem.

Error installing new package
Error loading package "n8n-nodes-telegram-client" :The specified package could not be loaded

n8n 1.67.1

**Comment by el-vis** [comment]
Hello. Same problem. Tried current and prev version.
Error loading package "n8n-nodes-telegram-client@0.1.7" :The specified package could not be loaded
Error loading package "n8n-nodes-telegram-client@0.1.6" :The specified package could not be loaded

**Comment by JedaiRussia** [comment]
I'm having the exact same problem.

**Comment by SlidEnergy** [comment]
I am too.
when install manually I've got error: require(...).TelegramClient is not a constructor

**Comment by jbjardine** [comment]
Same problem

**Comment by jbjardine** [comment]
`Dec 10 01:30:57 Error loading package "n8n-nodes-telegram-client" :The specified package could not be loaded
Dec 10 01:30:57 ResponseError: Error loading package "n8n-nodes-telegram-client" :The specified package could not be loaded
Dec 10 01:30:57 at CommunityPackagesController.installPackage (/app/code/node_modules/n8n/src/controllers/community-packages.controller.ts:111:10)
Dec 10 01:30:57 at processTicksAndRejections (node:internal/process/task_queues:95:5)
Dec 10 01:30:57 at handler (/app/code/node_modules/n8n/src/decorators/controller.registry.ts:105:12)
Dec 10 01:30:57 at /app/code/node_modules/n8n/src/response-helper.ts:162:17
Dec 10 01:30:57 2024-12-10T00:30:57Z`

**Comment by RomanGoryaynov** [comment]
Dear author, I probably know how to solve your problem: Register on https://www.npmjs.com/, then upload your "n8n-nodes-telegram-client" there and the problem will be solved

**Comment by RomanGoryaynov** [comment]
or look at it: https://community.n8n.io/t/how-to-use-telegram-mtproto-in-n8n/9472
